FROM node:6
LABEL io.whalebrew.name=cfn-create-or-update

# DEPRECATED

ENTRYPOINT ["echo", "This command is now deprecated. The official AWS CLI now provides the same functionality with the aws cloudformation deploy [...] --no-fail-on-empty-changeset"]
